version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: organizeu-postgres
    environment:
      POSTGRES_DB: organizeudb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Sambhav70+
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data: