version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: organizeu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organizeu_db
      MYSQL_USER: organizeu
      MYSQL_PASSWORD: organizeu123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: 